#
# Copyright (c) 2020, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  ex-know-your-customer-sandbox:
    image: digitalasset/ex-know-your-customer-sandbox:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-sandbox
    ports:
      - "127.0.0.1:6865:6865"

  ex-know-your-customer-triggers:
    image: digitalasset/ex-know-your-customer-triggers:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-triggers
    depends_on:
      - "ex-know-your-customer-sandbox"
    environment:
      - SANDBOX_HOST=ex-know-your-customer-sandbox
      - SANDBOX_PORT=6865

  ex-know-your-customer-bots:
    image: digitalasset/ex-know-your-customer-bots:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-bots
    depends_on:
      - "ex-know-your-customer-triggers"
    volumes:
      - ./data:/home/sdk/data
    environment:
      - SANDBOX_HOST=ex-know-your-customer-sandbox
      - SANDBOX_PORT=6865

  ex-know-your-customer-navigator:
    image: digitalasset/ex-know-your-customer-navigator:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-navigator
    depends_on:
      - "ex-know-your-customer-sandbox"
    ports:
      - "127.0.0.1:7500:7500"
    environment:
      - SANDBOX_HOST=ex-know-your-customer-sandbox
      - SANDBOX_PORT=6865
